/gate/source/addSource xraygun
/gate/source/verbose 0
/gate/source/xraygun/setActivity 1. MBq
/gate/source/xraygun/gps/verbose 0
/gate/source/xraygun/gps/particle gamma
/gate/source/xraygun/gps/energytype Mono
/gate/source/xraygun/gps/energy     140. keV
#/gate/source/xraygun/gps/setSpectrumFile Molybdenum_energySpectrumFluenceTrack.txt
/gate/source/xraygun/gps/type Plane
/gate/source/xraygun/gps/shape Rectangle
/gate/source/xraygun/gps/halfx 0.025 mm
/gate/source/xraygun/gps/halfy 0.025 mm
/gate/source/xraygun/gps/mintheta 0.  deg
/gate/source/xraygun/gps/maxtheta 20 deg
/gate/source/xraygun/gps/centre 0. 20. -100.0 cm
/gate/source/xraygun/gps/angtype iso
/gate/source/list
